### ISSUE TITLE
[BUG]failed cellfinder

### ISSUE THREAD

**Issue by cindy12-gao** [brainglobe/cellfinder#145]
**Describe the bug**
I`ve successfully made a registration between my background channel and atlas, but when I ran cellfinder, there is always error, which no atlas existing. 

**To Reproduce**
2020-10-13 17:51:48 PM - WARNING - MainProcess prep.py:405 - Atlas does not exist, downloading.

**Expected behavior**
I want detect brain signal and counting the cell signal in each brain area.

**Log file**

**Screenshots**
(cellfinder) C:\Users\CIBR-ImFacility-WS2>cellfinder -s H:\cellfinder_data_test\signal -b H:\cellfinder_data_test\background -o H:\cellfinder_data_test\output --register --orientation coronal -x 1.625 -y 3 -z 1.625
2020-10-13 17:51:48 PM - INFO - MainProcess fancylog.py:267 - Starting logging
Downloading...
2020-10-13 17:51:48 PM - INFO - MainProcess fancylog.py:269 - Multiprocessing-logging module found. Logging from all processes
2020-10-13 17:51:48 PM - INFO - MainProcess main.py:32 - Registering to atlas
2020-10-13 17:51:48 PM - INFO - MainProcess prep.py:401 - Checking whether the atlas exists
2020-10-13 17:51:48 PM - WARNING - MainProcess prep.py:405 - Atlas does not exist, downloading.

**Desktop (please complete the following information):**
 - OS: Windows
 - Version10 pro for station
- Hardware specs  640GB RAM, Xeon 6136 CPU

**Additional context**
my order:
cellfinder -s H:\cellfinder_data_test\signal -b H:\cellfinder_data_test\background -o H:\cellfinder_data_test\output --register --orientation coronal -x 1.625 -y 3 -z 1.625

and it also confuse  me that do I need define the orientation(coronal) asl just like the definition of brainreg? @adamltyson

**Comment by cindy12-gao** [comment]
[cellfinder_2020-10-13_17-51-48.log](https://github.com/brainglobe/cellfinder/files/5370603/cellfinder_2020-10-13_17-51-48.log)

**Comment by adamltyson** [comment]
Hi @cindy12-gao, that warning is just that, a warning, it's not an issue. The software will just download the atlas that it needs.

That being said, I think there might be an incompatibility between the (newer) version of brainreg and the version of cellfinder you have. Could you try creating a new conda environment and installing the new version of cellfinder (`pip install cellfinder==0.4.0`)? 

You will get version `0.4.0`, which unfortunately is a fairly major change, and the usage instructions have changed. You can find the release notes [here](https://docs.brainglobe.info/cellfinder/release-notes#version-0-4-0-tbc), new instructions [here](https://docs.brainglobe.info/cellfinder/user-guide), and a tutorial [here](https://docs.brainglobe.info/cellfinder/tutorial).

The main changes (for you, based on your command is that):
* The registration will run by default (no need for the `--register` flag)
* You will need to enter the voxel sizes in the same way as brainreg (e.g. `-v 1.625 3 1.625`)
* You will need to enter the orientation in the same way as brainreg. If your data is coronal, it will likely be `--orientation psl` if you image from the back of the brain, or `--orientation asr` if you image from the front.


One last point, I just want to check your pixel sizes. Did you re-slice your data (e.g. from a horizontal acquisition to coronal)? I ask because it would be weird for you to have a z resolution (plane spacing) of 1.625 microns, and then an in plane resolution of 1.625 x 3 microns. If this is all right, then no problem! 

Either way, the new way of entering your voxel sizes should be `-v A B C` where:
* `A` is the voxel spacing between image planes
* `B` is the voxel spacing vertically (if you open a single image in napari/FIJI etc.)
* `C` is the voxel spacing horizontally (if you open a single image in napari/FIJI etc.)

**Comment by cindy12-gao** [comment]
thank you for your answer~ I`ve tried the version 0.4.0, it works well, and the -v definition I think is right. the data was captured by lightsheet and the orientation was horizontal, and then I rotated it to the coronal , so that`s why the -V was strange. 
then there also was a problem that I can`t detect any cell from my data. the order as follows:
cellfinder -s H:\cellfinder_data_test\signal -b H:\cellfinder_data_test\background -o H:\cellfinder_data_test\output -v 1.625 3 1.625 --orientation asl --no-register --start-plane 3000 --end-plane 3020 --soma-diameter 3

**Comment by adamltyson** [comment]
>  the data was captured by lightsheet and the orientation was horizontal, and then I rotated it to the coronal 

Ok great, that makes sense.

Your parameters look ok, but I would check two things:
* ` --start-plane 3000 --end-plane 3020` These parameters are a bit confusing, as the software needs to "see" the whole cell in the first dimension (i.e. through the image planes). 20 planes for you is only 32um, so there may not be many cells in that range
* `--soma-diameter 3` This is very low, are your cells really only 3um across?

**Comment by cindy12-gao** [comment]
actually, I`ve tested the whole brain slice, and the cell diameter was default, and the results shows no cell detected;
so I analysis only 20 planes just want to test the parameter. I`m confused why there is no cell detected?

**Comment by adamltyson** [comment]
>  Im confused why there is no cell detected?

I can't really tell without seeing the data. Are you able to share the whole image?

**Comment by cindy12-gao** [comment]
![signal_coronal3000](https://user-images.githubusercontent.com/72720700/96447455-826a1b00-1244-11eb-829b-9e2ead8c0656.png)
![signal_coronal3001](https://user-images.githubusercontent.com/72720700/96447465-84cc7500-1244-11eb-93f1-67676f8b8fe0.png)
it`s the plane3000 and the plane 3001.

**Comment by adamltyson** [comment]
Hi @cindy12-gao, it looks like you have pretty low SNR and resolution. I can't say much more without seeing the full data.

Is your problem that you see no cell candidates, or no classified cells?

**Comment by cindy12-gao** [comment]
[cellfinder_2020-10-19_18-26-02.log](https://github.com/brainglobe/cellfinder/files/5401602/cellfinder_2020-10-19_18-26-02.log)
it`s the log file. I saved the data as PNG, maybe loss some resolution

**Comment by adamltyson** [comment]
Ok, so no cell candidates have been detected. If you can send me the data, I can take a look, otherwise I can only recommend adjusting the detection parameters.

**Comment by cindy12-gao** [comment]
it`s almost 200GB, I`m not sure how to send you my data.

**Comment by adamltyson** [comment]
Do you have Dropbox, or some kind of institutional file sharing platform?

If you could send me 100 or so consecutive planes, that would help.

**Comment by cindy12-gao** [comment]
I`ve shared the folder signal&background with the email address--notifications@github.com by Dropbox.I`m not sure whether you can view the data. hope for your reply! thank you~

**Comment by adamltyson** [comment]
I think that address is just the email address GitHub send emails from. Could you share it with `adam.tyson@ucl.ac.uk`?

Thanks!

**Comment by cindy12-gao** [comment]
ok, I`ve share the folder with this email address. thank you~


------------------------------------------------------------------
发件人：Adam Tyson <notifications@github.com>
发送时间：2020年10月20日(星期二) 18:49
收件人：brainglobe/cellfinder <cellfinder@noreply.github.com>
抄　送：高辛未 <gaoxinwei@cibr.ac.cn>; Mention <mention@noreply.github.com>
主　题：Re: [brainglobe/cellfinder] [BUG]failed cellfinder (#145)

I think that address is just the email address GitHub send emails from. Could you share it with adam.tyson@ucl.ac.uk?
Thanks!

**Comment by adamltyson** [comment]
Thanks for sending the data @cindy12-gao, I haven't forgotten, I'm just a bit swamped at the moment.

**Comment by cindy12-gao** [comment]
it doesn`t matter. can you try to detect signal from the data?


------------------------------------------------------------------
发件人：Adam Tyson <notifications@github.com>
发送时间：2020年11月5日(星期四) 18:07
收件人：brainglobe/cellfinder <cellfinder@noreply.github.com>
抄　送：高辛未 <gaoxinwei@cibr.ac.cn>; Mention <mention@noreply.github.com>
主　题：Re: [brainglobe/cellfinder] [BUG]failed cellfinder (#145)

Thanks for sending the data @cindy12-gao, I haven't forgotten, I'm just a bit swamped at the moment.

**Comment by adamltyson** [comment]
Hi @cindy12-gao, I had a look at your data, and I found that the reason you weren't detecting any cell candidates was because there's a very narrow border of zero intensity around your images. cellfinder assumes that the very edges of your image contain background signal, so this messed up the detection. I've fixed this, and now candidates are detected.

![detection](https://user-images.githubusercontent.com/13147259/98378938-9a141280-203e-11eb-8f26-409e9d1c6e11.png)

The cell detection works ok (but still needs optimising) with the default parameters, but the classification is very bad. I think this is due to three things:
* The data is very different to the training set, you will need to retrain it
* The image channels aren't aligned very well, can this be improved?
* The classification network assumes that the first dimension in your dataset corresponds to the axial plane. Can you rerun cellfinder with the original, horizontally acquired data?

Lastly, there are a lot of striping and stitching artefacts in the data, without this being fixed (and the channel alignment), you may not get very good analysis results.

P.S. I'll release the new, updated version of cellfinder later today. By tomorrow, you should be able to run `pip install cellfinder --upgrade` to get the new version. Can you let me know if this works?

**Comment by cindy12-gao** [comment]
thank you! can you send me the fixed parameters of the cell detection? it`ll teach me how to set the parameter.


------------------------------------------------------------------
发件人：Adam Tyson <notifications@github.com>
发送时间：2020年11月6日(星期五) 22:53
收件人：brainglobe/cellfinder <cellfinder@noreply.github.com>
抄　送：高辛未 <gaoxinwei@cibr.ac.cn>; Mention <mention@noreply.github.com>
主　题：Re: [brainglobe/cellfinder] [BUG]failed cellfinder (#145)

Hi @cindy12-gao, I had a look at your data, and I found that the reason you weren't detecting any cell candidates was because there's a very narrow border of zero intensity around your images. cellfinder assumes that the very edges of your image contain background signal, so this messed up the detection. I've fixed this, and now candidates are detected.
[detection]
The cell detection works ok (but still needs optimising) with the default parameters, but the classification is very bad. I think this is due to three things:
The data is very different to the training set, you will need to retrain it
The image channels aren't aligned very well, can this be improved?
The classification network assumes that the first dimension in your dataset corresponds to the axial plane. Can you rerun cellfinder with the original, horizontally acquired data?
Lastly, there are a lot of striping and stitching artefacts in the data, without this being fixed (and the channel alignment), you may not get very good analysis results.
P.S. I'll release the new, updated version of cellfinder later today. By tomorrow, you should be able to run pip install cellfinder --upgrade to get the new version. Can you let me know if this works?

**Comment by adamltyson** [comment]
I didn’t optimise the cell detection, I just used the default parameters. 

Is the new software version working for you?

**Comment by cindy12-gao** [comment]
I`ve updated the version cellfinder==0.4.5
