### ISSUE TITLE
[Feature] Cells data extraction

### ISSUE THREAD

**Issue by FedeClaudi** [brainglobe/cellfinder#15]
**Is your feature request related to a problem? Please describe.**
I know that there are a few ways to export data about the detected cells (e.g. `cellfinder_cells_to_brainrender`),  but it would be good to be able to export the following as a table, for each cell:

- `x,y,z` and `radius` in raw data coordinates
- `x,y,z` and `radius` in standard space
- `brain region` according to the Allen atlas. Perhaps even the whole hierarchy of brain structures the region is in (e.g. `Gray\isocortex\MOs\MOs5b`)
- `hemisphere`

This would make it a lot easier to import this data into other analysis and visualisation pipelines. 
In fact I suggest this should be done automatically once the analysis is completed.

**Comment by adamltyson** [comment]
So that's all possible (apart from `radius`, as there's no way to extract that with cellfinder).

So would something like this work (in both sample and standard space)?


| x    | y    | z    | Region                       | Hemisphere |
|------|------|------|------------------------------|------------|
| 1000 | 1250 | 1500 | Somatomotor areas, Layer 1   | Left       |
| 2000 | 50   | 100  | Lateral visual area, layer 1 | Right      |

Or would you rather them all in one csv?

| x    | y    | z    | transformed x | transformed y| transformed y| Region                       | Hemisphere |
|------|------|------|------|------|------|------------------------------|------------|
| 1000 | 1250 | 1500 | 1010 | 1260 | 1505 |Somatomotor areas, Layer 1   | Left       |
| 2000 | 50   | 100  | 2100 | 56   | 104  | Lateral visual area, layer 1 | Right      |


What kind of analysis/visualisation are you planning on? I'm working on another tool, `cellfinder-analyst` which will incorporate group-level analyses.

**Comment by FedeClaudi** [comment]
I think that having it all in one csv would be the easier.

It's not so much for anything I had planned, but more something that would be useful in general. This is the kind of output that one would use for any kind of analysis/visualisation outside of cellfinder so it'd be good to have an option to generate this data. 

For instance in a cluttered scene one might want to look at cells in one brain region at the time (e.g. to see in which subdivision of the region are located). 

As an example here in brainreder I just visualise the cells in the isocortex:

```
cells = pd.read_hdf(cellsfile)

# ... find in which structure each cell is and add it to the data frame ...

# Select only cells in the isocortex
regions = scene.get_structure_descendants('Isocortex').acronym
cells = cells.loc[cells.region.isin(regions)]
```

<img width="889" alt="image" src="https://user-images.githubusercontent.com/17436313/72840219-aaaff380-3c8b-11ea-96f5-66987754c466.png">


But to do this I had to determined in which region each cell is from its coordinates. 
This is fairly easy and fast to do in BrainRender but it'd be even easier to just have it in a .csv or .h5 file.

**Comment by adamltyson** [comment]
Took nearly a year, but this is added in 476ccb1a5576e0936f7d71a635fb5fc70731b1e5.

There is now a file saved by default (`cellfinder_output/analysis/all_points.csv`) which looks something like:
| coordinate_raw_axis_0 | coordinate_raw_axis_1 | coordinate_raw_axis_2 | coordinate_atlas_axis_0 | coordinate_atlas_axis_1 | coordinate_atlas_axis_2 | structure_name                            | hemisphere |
|-----------------------|-----------------------|-----------------------|-------------------------|-------------------------|-------------------------|-------------------------------------------|------------|
| 638                   | 3475                  | 771                   | 928                     | 104                     | 774                     | Primary visual area, layer 5              | left       |
| 638                   | 3554                  | 653                   | 937                     | 79                      | 794                     | Primary visual area, layer 2/3            | left       |
| 638                   | 3554                  | 772                   | 929                     | 103                     | 792                     | Primary visual area, layer 4              | left       |
| 638                   | 3574                  | 717                   | 932                     | 93                      | 798                     | Primary visual area, layer 2/3            | left       |
| 638                   | 3665                  | 707                   | 933                     | 88                      | 820                     | Primary visual area, layer 2/3            | left       |
| 638                   | 3685                  | 726                   | 931                     | 92                      | 824                     | Primary visual area, layer 2/3            | left       |
| 638                   | 3693                  | 777                   | 928                     | 103                     | 824                     | Primary visual area, layer 2/3            | left       |


There's no hierarchy because not every BrainGlobe atlas will necessarily have a hierarchy (and I'm lazy).
