### ISSUE TITLE
the confusion of the definition of orientation

### ISSUE THREAD

**Issue by cindy12-gao** [brainglobe/cellfinder#158]
hello~
![20201207-demowholebrain-two channels-rotate_C0_Z4194](https://user-images.githubusercontent.com/72720700/101741083-9889ae80-3b04-11eb-8f93-274e4e02a9f1.png)

if my data is like this, how to define the data`s orientation. the beginning slice is olfactory bulb area.
--orientation abr?   or only two orientation asl&psl can be recognized?

**Comment by cindy12-gao** [comment]
![Uploading 20201207-demowholebrain-two channels-rotate_C0_Z4194.png…]()

**Comment by adamltyson** [comment]
Hi,

Any orientation of data is supported, there are more details on the [bg-space](https://github.com/brainglobe/bg-space) page.

If the first slice is olfactory bulb, then:
* The first axis origin is **a**nterior
* The second axis (top-bottom) origin is **i**nferior
* The third axis (left-right) origin is (presumably, but check) **l**eft

The orientation for passing to cellfinder is then `ail`.

For usage questions (rather than bug reports etc), would you mind using the gitter help forum, it's helpful to have all of these usage questions in one place. There's a channel for [cellfinder](https://gitter.im/BrainGlobe/cellfinder) and [brainreg](https://gitter.im/BrainGlobe/brainreg) (among others). Thanks!
