### ISSUE TITLE
Investigate why there's a transpose operation that cannot be removed. 

### ISSUE THREAD

**Issue by adamltyson** [brainglobe/cellfinder#411]
[This comment](https://github.com/brainglobe/brainglobe-utils/pull/67#issuecomment-2070749047) from @matham highlights that there is a transpose that, if removed, causes errors. 

In theory cellfinder shouldn't require a specific axis order, so it would be good to know why this tranpose is there.

cc @alessandrofelder

**Comment by matham** [comment]
I did find the cause, there is another place, [here](https://github.com/brainglobe/cellfinder/blob/e6a887f1721b89d51328214b108e0da5401a24a9/cellfinder/core/detect/filters/setup_filters.py#L29), where it's flipped. And both places have to be fixed to make it work. I ran into it during further pytorch stuff and removing both flips fixed the issue.

**Comment by adamltyson** [comment]
Thanks @matham, I think I'm missing something though, where is the second flip?

**Comment by matham** [comment]
Right, because in some places, the assumption seems to be that the order is `x, y`, e.g. [here](https://github.com/brainglobe/cellfinder/blob/e6a887f1721b89d51328214b108e0da5401a24a9/cellfinder/core/detect/filters/volume/ball_filter.py#L107). Which means, when you pass planes to e.g. the ball filter, it needs to have that order. But I guess there was an assumption that the data comes in `y, x`, like in the link in the last message. So it has to be flipped to make it work with the filter. 

But, if it used a consistent order with arbitrary dim1/dim2, it should not need flipping anywhere. And in my pytorch code that seemed to work ok.

**Comment by adamltyson** [comment]
Thanks for clarifying, I saw your previous link and it looked correct, because it was normal numpy axis ordering. So it seems like there's a mix of numpy and cartesian axis ordering, and we should decide on one.

Everywhere else in BrainGlobe where we've made this decision, we've gone with numpy, so I propose we do the same here. Any issue @brainglobe/active-devs?

**Comment by alessandrofelder** [comment]
My initial instinct would be to implement 2. soon (it's a concrete, scoped step that will avoid unnecessary computations) and leave 3. for a later time point, as we have more pressing issues in the roadmap?
